apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-blog
  template:
    metadata:
      labels:
        app: wordpress-blog
    spec:
      containers:
      - name: wordpress-blog  
        image: acrwordraizenproject.azurecr.io/mybloglive:v1
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "dbprojectraizendev000.mysql.database.azure.com" #Update here
        - name: DATABASE_USERNAME
          value: "admin_raizen_dev"  #Update here
        - name: DATABASE_PASSWORD
          value: "Fimdenoite01"  #Update here
        - name: DATABASE_NAME
          value: "flexibleserverdb"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - wordpress-blog
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wordpress-blog