apiVersion : apps/v1
kind: Deployment
metadata:
  name: projetoraizenwordpress 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projetoraizenwordpress
  template:
    metadata:
      labels:
        app: projetoraizenwordpress 
    spec:
      containers:
        - name: projetoraizenwordpress 
          image: acrwordraizenproject.azurecr.io/projetoraizenwordpress
          ports:
          - containerPort: 80